interface RawDetailAttributes {
	accounting_expense_range?: string;
	accounting_expense_total?: string;
	advertising_expense_range?: string;
	advertising_expense_total?: string;
	business_insurance_expense_range?: string;
	business_insurance_expense_total?: string;
	business_status?: string;
	business_type?: string;
	carrier_route?: string;
	census_block?: string;
	census_tract?: string;
	city_name?: string;
	company_name?: string;
	company_name_secondary?: string;
	contact_first_name?: string;
	contact_full_name?: string;
	contact_gender?: string;
	contact_last_name?: string;
	contact_middle_name?: string;
	contact_prefix?: string;
	contact_professional_title?: string;
	contact_suffix?: string;
	core_based_stat_area_code?: string;
	core_based_stat_area_name?: string;
	corporate_employee_count_range?: string;
	corporate_employee_count_total?: string;
	county_fips?: string;
	county_name?: string;
	credit_capacity?: string;
	credit_capacity_range?: string;
	credit_score?: string;
	credit_score_description?: string;
	date_of_last_update?: string;
	delivery_line_1?: string;
	delivery_point?: string;
	delivery_point_check_digit?: string;
	domestic_foreign_owner_indicator?: string;
	ein?: string;
	email?: string;
	email_available_indicator?: string;
	executive_department?: string;
	executive_level?: string;
	executive_verification_type?: string;
	fax?: string;
	female_owned_indicator?: string;
	foreign_parent_city_name?: string;
	foreign_parent_company_name?: string;
	foreign_parent_country?: string;
	fortune_1000_branches?: string;
	fortune_1000_indicator?: string;
	fortune_1000_rank?: string;
	holding_city_name?: string;
	holding_company_name?: string;
	holding_id?: string;
	holding_state_abbreviation?: string;
	home_based_business_indicator?: string;
	hq_city_name?: string;
	hq_company_name?: string;
	hq_id?: string;
	hq_number_of_companies?: string;
	hq_state_abbreviation?: string;
	latitude?: string;
	legal_expense_range?: string;
	legal_expense_total?: string;
	linkage_company_name?: string;
	linkage_indicator?: string;
	linkage_level?: string;
	linkage_type?: string;
	location_employee_count?: string;
	location_employee_count_range?: string;
	location_sales_range?: string;
	location_sales_total?: string;
	longitude?: string;
	mail_score_code?: string;
	mail_score_description?: string;
	mailing_carrier_route?: string;
	mailing_city_name?: string;
	mailing_delivery_line_1?: string;
	mailing_delivery_point?: string;
	mailing_delivery_point_check_digit?: string;
	mailing_plus4_code?: string;
	mailing_state_abbreviation?: string;
	mailing_zipcode?: string;
	manufacturing_indicator?: string;
	minority_owned_indicator?: string;
	minority_type?: string;
	naics_01_code?: string;
	naics_01_description?: string;
	naics_02_code?: string;
	naics_02_description?: string;
	naics_03_code?: string;
	naics_03_description?: string;
	naics_04_code?: string;
	naics_04_description?: string;
	naics_05_code?: string;
	naics_05_description?: string;
	naics_06_code?: string;
	naics_06_description?: string;
	new_business_indicator?: string;
	non_profit_indicator?: string;
	num_of_pcs_range?: string;
	num_of_pcs_total?: string;
	number_of_years_in_business?: string;
	number_of_years_in_business_range?: string;
	office_equipment_expense_range?: string;
	office_equipment_expense_total?: string;
	operating_hours_friday?: string;
	operating_hours_monday?: string;
	operating_hours_saturday?: string;
	operating_hours_sunday?: string;
	operating_hours_thursday?: string;
	operating_hours_tuesday?: string;
	operating_hours_wednesday?: string;
	phone?: string;
	phone_area_code?: string;
	phone_secondary?: string;
	phone_toll_free?: string;
	plus4_code?: string;
	population_range?: string;
	precision?: string;
	primary_executive_indicator?: string;
	primary_number?: string;
	primary_sic_2digit_code?: string;
	primary_sic_2digit_description?: string;
	primary_sic_4digit_code?: string;
	primary_sic_4digit_description?: string;
	primary_sic_code?: string;
	primary_sic_description?: string;
	public_indicator?: string;
	rdi?: string;
	rent_expense_range?: string;
	rent_expense_total?: string;
	secondary_01_sic_7digit_code?: string;
	secondary_01_sic_7digit_description?: string;
	secondary_02_sic_7digit_code?: string;
	secondary_02_sic_7digit_description?: string;
	secondary_03_sic_7digit_code?: string;
	secondary_03_sic_7digit_description?: string;
	secondary_04_sic_7digit_code?: string;
	secondary_04_sic_7digit_description?: string;
	secondary_05_sic_7digit_code?: string;
	secondary_05_sic_7digit_description?: string;
	secondary_designator?: string;
	secondary_number?: string;
	sectional_center_facility?: string;
	small_business_indicator?: string;
	source_title?: string;
	square_footage?: string;
	square_footage_range?: string;
	standardized_title?: string;
	standardized_title_rank?: string;
	state_abbreviation?: string;
	stock_exchange?: string;
	street_name?: string;
	street_postdirection?: string;
	street_predirection?: string;
	street_suffix?: string;
	sub_hq_city_name?: string;
	sub_hq_company_name?: string;
	sub_hq_id?: string;
	sub_hq_number_of_companies?: string;
	sub_hq_state_abbreviation?: string;
	technology_expense_range?: string;
	technology_expense_total?: string;
	telecom_expense_range?: string;
	telecom_expense_total?: string;
	ticker_symbol?: string;
	time_zone?: string;
	url?: string;
	url_facebook?: string;
	url_instagram?: string;
	url_linkedin?: string;
	url_twitter?: string;
	url_yelp?: string;
	url_youtube?: string;
	utilities_expense_range?: string;
	utilities_expense_total?: string;
	webmail_indicator?: string;
	year_current?: string;
	year_current_employee_count?: string;
	year_established?: string;
	year_four_prior?: string;
	year_four_prior_employee_count?: string;
	year_four_prior_employee_growth?: string;
	year_one_prior?: string;
	year_one_prior_employee_count?: string;
	year_one_prior_employee_growth?: string;
	year_three_prior?: string;
	year_three_prior_employee_count?: string;
	year_three_prior_employee_growth?: string;
	year_two_prior?: string;
	year_two_prior_employee_count?: string;
	year_two_prior_employee_growth?: string;
	zipcode?: string;
}

export default class DetailAttributes {
	accountingExpenseRange: string | undefined;
	accountingExpenseTotal: string | undefined;
	advertisingExpenseRange: string | undefined;
	advertisingExpenseTotal: string | undefined;
	businessInsuranceExpenseRange: string | undefined;
	businessInsuranceExpenseTotal: string | undefined;
	businessStatus: string | undefined;
	businessType: string | undefined;
	carrierRoute: string | undefined;
	censusBlock: string | undefined;
	censusTract: string | undefined;
	cityName: string | undefined;
	companyName: string | undefined;
	companyNameSecondary: string | undefined;
	contactFirstName: string | undefined;
	contactFullName: string | undefined;
	contactGender: string | undefined;
	contactLastName: string | undefined;
	contactMiddleName: string | undefined;
	contactPrefix: string | undefined;
	contactProfessionalTitle: string | undefined;
	contactSuffix: string | undefined;
	coreBasedStatAreaCode: string | undefined;
	coreBasedStatAreaName: string | undefined;
	corporateEmployeeCountRange: string | undefined;
	corporateEmployeeCountTotal: string | undefined;
	countyFips: string | undefined;
	countyName: string | undefined;
	creditCapacity: string | undefined;
	creditCapacityRange: string | undefined;
	creditScore: string | undefined;
	creditScoreDescription: string | undefined;
	dateOfLastUpdate: string | undefined;
	deliveryLine1: string | undefined;
	deliveryPoint: string | undefined;
	deliveryPointCheckDigit: string | undefined;
	domesticForeignOwnerIndicator: string | undefined;
	ein: string | undefined;
	email: string | undefined;
	emailAvailableIndicator: string | undefined;
	executiveDepartment: string | undefined;
	executiveLevel: string | undefined;
	executiveVerificationType: string | undefined;
	fax: string | undefined;
	femaleOwnedIndicator: string | undefined;
	foreignParentCityName: string | undefined;
	foreignParentCompanyName: string | undefined;
	foreignParentCountry: string | undefined;
	fortune1000Branches: string | undefined;
	fortune1000Indicator: string | undefined;
	fortune1000Rank: string | undefined;
	holdingCityName: string | undefined;
	holdingCompanyName: string | undefined;
	holdingId: string | undefined;
	holdingStateAbbreviation: string | undefined;
	homeBasedBusinessIndicator: string | undefined;
	hqCityName: string | undefined;
	hqCompanyName: string | undefined;
	hqId: string | undefined;
	hqNumberOfCompanies: string | undefined;
	hqStateAbbreviation: string | undefined;
	latitude: string | undefined;
	legalExpenseRange: string | undefined;
	legalExpenseTotal: string | undefined;
	linkageCompanyName: string | undefined;
	linkageIndicator: string | undefined;
	linkageLevel: string | undefined;
	linkageType: string | undefined;
	locationEmployeeCount: string | undefined;
	locationEmployeeCountRange: string | undefined;
	locationSalesRange: string | undefined;
	locationSalesTotal: string | undefined;
	longitude: string | undefined;
	mailScoreCode: string | undefined;
	mailScoreDescription: string | undefined;
	mailingCarrierRoute: string | undefined;
	mailingCityName: string | undefined;
	mailingDeliveryLine1: string | undefined;
	mailingDeliveryPoint: string | undefined;
	mailingDeliveryPointCheckDigit: string | undefined;
	mailingPlus4Code: string | undefined;
	mailingStateAbbreviation: string | undefined;
	mailingZipcode: string | undefined;
	manufacturingIndicator: string | undefined;
	minorityOwnedIndicator: string | undefined;
	minorityType: string | undefined;
	naics01Code: string | undefined;
	naics01Description: string | undefined;
	naics02Code: string | undefined;
	naics02Description: string | undefined;
	naics03Code: string | undefined;
	naics03Description: string | undefined;
	naics04Code: string | undefined;
	naics04Description: string | undefined;
	naics05Code: string | undefined;
	naics05Description: string | undefined;
	naics06Code: string | undefined;
	naics06Description: string | undefined;
	newBusinessIndicator: string | undefined;
	nonProfitIndicator: string | undefined;
	numOfPcsRange: string | undefined;
	numOfPcsTotal: string | undefined;
	numberOfYearsInBusiness: string | undefined;
	numberOfYearsInBusinessRange: string | undefined;
	officeEquipmentExpenseRange: string | undefined;
	officeEquipmentExpenseTotal: string | undefined;
	operatingHoursFriday: string | undefined;
	operatingHoursMonday: string | undefined;
	operatingHoursSaturday: string | undefined;
	operatingHoursSunday: string | undefined;
	operatingHoursThursday: string | undefined;
	operatingHoursTuesday: string | undefined;
	operatingHoursWednesday: string | undefined;
	phone: string | undefined;
	phoneAreaCode: string | undefined;
	phoneSecondary: string | undefined;
	phoneTollFree: string | undefined;
	plus4Code: string | undefined;
	populationRange: string | undefined;
	precision: string | undefined;
	primaryExecutiveIndicator: string | undefined;
	primaryNumber: string | undefined;
	primarySic2DigitCode: string | undefined;
	primarySic2DigitDescription: string | undefined;
	primarySic4DigitCode: string | undefined;
	primarySic4DigitDescription: string | undefined;
	primarySicCode: string | undefined;
	primarySicDescription: string | undefined;
	publicIndicator: string | undefined;
	rdi: string | undefined;
	rentExpenseRange: string | undefined;
	rentExpenseTotal: string | undefined;
	secondary01Sic7DigitCode: string | undefined;
	secondary01Sic7DigitDescription: string | undefined;
	secondary02Sic7DigitCode: string | undefined;
	secondary02Sic7DigitDescription: string | undefined;
	secondary03Sic7DigitCode: string | undefined;
	secondary03Sic7DigitDescription: string | undefined;
	secondary04Sic7DigitCode: string | undefined;
	secondary04Sic7DigitDescription: string | undefined;
	secondary05Sic7DigitCode: string | undefined;
	secondary05Sic7DigitDescription: string | undefined;
	secondaryDesignator: string | undefined;
	secondaryNumber: string | undefined;
	sectionalCenterFacility: string | undefined;
	smallBusinessIndicator: string | undefined;
	sourceTitle: string | undefined;
	squareFootage: string | undefined;
	squareFootageRange: string | undefined;
	standardizedTitle: string | undefined;
	standardizedTitleRank: string | undefined;
	stateAbbreviation: string | undefined;
	stockExchange: string | undefined;
	streetName: string | undefined;
	streetPostdirection: string | undefined;
	streetPredirection: string | undefined;
	streetSuffix: string | undefined;
	subHqCityName: string | undefined;
	subHqCompanyName: string | undefined;
	subHqId: string | undefined;
	subHqNumberOfCompanies: string | undefined;
	subHqStateAbbreviation: string | undefined;
	technologyExpenseRange: string | undefined;
	technologyExpenseTotal: string | undefined;
	telecomExpenseRange: string | undefined;
	telecomExpenseTotal: string | undefined;
	tickerSymbol: string | undefined;
	timeZone: string | undefined;
	url: string | undefined;
	urlFacebook: string | undefined;
	urlInstagram: string | undefined;
	urlLinkedin: string | undefined;
	urlTwitter: string | undefined;
	urlYelp: string | undefined;
	urlYoutube: string | undefined;
	utilitiesExpenseRange: string | undefined;
	utilitiesExpenseTotal: string | undefined;
	webmailIndicator: string | undefined;
	yearCurrent: string | undefined;
	yearCurrentEmployeeCount: string | undefined;
	yearEstablished: string | undefined;
	yearFourPrior: string | undefined;
	yearFourPriorEmployeeCount: string | undefined;
	yearFourPriorEmployeeGrowth: string | undefined;
	yearOnePrior: string | undefined;
	yearOnePriorEmployeeCount: string | undefined;
	yearOnePriorEmployeeGrowth: string | undefined;
	yearThreePrior: string | undefined;
	yearThreePriorEmployeeCount: string | undefined;
	yearThreePriorEmployeeGrowth: string | undefined;
	yearTwoPrior: string | undefined;
	yearTwoPriorEmployeeCount: string | undefined;
	yearTwoPriorEmployeeGrowth: string | undefined;
	zipcode: string | undefined;

	constructor(raw?: RawDetailAttributes) {
		this.accountingExpenseRange = raw?.accounting_expense_range;
		this.accountingExpenseTotal = raw?.accounting_expense_total;
		this.advertisingExpenseRange = raw?.advertising_expense_range;
		this.advertisingExpenseTotal = raw?.advertising_expense_total;
		this.businessInsuranceExpenseRange = raw?.business_insurance_expense_range;
		this.businessInsuranceExpenseTotal = raw?.business_insurance_expense_total;
		this.businessStatus = raw?.business_status;
		this.businessType = raw?.business_type;
		this.carrierRoute = raw?.carrier_route;
		this.censusBlock = raw?.census_block;
		this.censusTract = raw?.census_tract;
		this.cityName = raw?.city_name;
		this.companyName = raw?.company_name;
		this.companyNameSecondary = raw?.company_name_secondary;
		this.contactFirstName = raw?.contact_first_name;
		this.contactFullName = raw?.contact_full_name;
		this.contactGender = raw?.contact_gender;
		this.contactLastName = raw?.contact_last_name;
		this.contactMiddleName = raw?.contact_middle_name;
		this.contactPrefix = raw?.contact_prefix;
		this.contactProfessionalTitle = raw?.contact_professional_title;
		this.contactSuffix = raw?.contact_suffix;
		this.coreBasedStatAreaCode = raw?.core_based_stat_area_code;
		this.coreBasedStatAreaName = raw?.core_based_stat_area_name;
		this.corporateEmployeeCountRange = raw?.corporate_employee_count_range;
		this.corporateEmployeeCountTotal = raw?.corporate_employee_count_total;
		this.countyFips = raw?.county_fips;
		this.countyName = raw?.county_name;
		this.creditCapacity = raw?.credit_capacity;
		this.creditCapacityRange = raw?.credit_capacity_range;
		this.creditScore = raw?.credit_score;
		this.creditScoreDescription = raw?.credit_score_description;
		this.dateOfLastUpdate = raw?.date_of_last_update;
		this.deliveryLine1 = raw?.delivery_line_1;
		this.deliveryPoint = raw?.delivery_point;
		this.deliveryPointCheckDigit = raw?.delivery_point_check_digit;
		this.domesticForeignOwnerIndicator = raw?.domestic_foreign_owner_indicator;
		this.ein = raw?.ein;
		this.email = raw?.email;
		this.emailAvailableIndicator = raw?.email_available_indicator;
		this.executiveDepartment = raw?.executive_department;
		this.executiveLevel = raw?.executive_level;
		this.executiveVerificationType = raw?.executive_verification_type;
		this.fax = raw?.fax;
		this.femaleOwnedIndicator = raw?.female_owned_indicator;
		this.foreignParentCityName = raw?.foreign_parent_city_name;
		this.foreignParentCompanyName = raw?.foreign_parent_company_name;
		this.foreignParentCountry = raw?.foreign_parent_country;
		this.fortune1000Branches = raw?.fortune_1000_branches;
		this.fortune1000Indicator = raw?.fortune_1000_indicator;
		this.fortune1000Rank = raw?.fortune_1000_rank;
		this.holdingCityName = raw?.holding_city_name;
		this.holdingCompanyName = raw?.holding_company_name;
		this.holdingId = raw?.holding_id;
		this.holdingStateAbbreviation = raw?.holding_state_abbreviation;
		this.homeBasedBusinessIndicator = raw?.home_based_business_indicator;
		this.hqCityName = raw?.hq_city_name;
		this.hqCompanyName = raw?.hq_company_name;
		this.hqId = raw?.hq_id;
		this.hqNumberOfCompanies = raw?.hq_number_of_companies;
		this.hqStateAbbreviation = raw?.hq_state_abbreviation;
		this.latitude = raw?.latitude;
		this.legalExpenseRange = raw?.legal_expense_range;
		this.legalExpenseTotal = raw?.legal_expense_total;
		this.linkageCompanyName = raw?.linkage_company_name;
		this.linkageIndicator = raw?.linkage_indicator;
		this.linkageLevel = raw?.linkage_level;
		this.linkageType = raw?.linkage_type;
		this.locationEmployeeCount = raw?.location_employee_count;
		this.locationEmployeeCountRange = raw?.location_employee_count_range;
		this.locationSalesRange = raw?.location_sales_range;
		this.locationSalesTotal = raw?.location_sales_total;
		this.longitude = raw?.longitude;
		this.mailScoreCode = raw?.mail_score_code;
		this.mailScoreDescription = raw?.mail_score_description;
		this.mailingCarrierRoute = raw?.mailing_carrier_route;
		this.mailingCityName = raw?.mailing_city_name;
		this.mailingDeliveryLine1 = raw?.mailing_delivery_line_1;
		this.mailingDeliveryPoint = raw?.mailing_delivery_point;
		this.mailingDeliveryPointCheckDigit = raw?.mailing_delivery_point_check_digit;
		this.mailingPlus4Code = raw?.mailing_plus4_code;
		this.mailingStateAbbreviation = raw?.mailing_state_abbreviation;
		this.mailingZipcode = raw?.mailing_zipcode;
		this.manufacturingIndicator = raw?.manufacturing_indicator;
		this.minorityOwnedIndicator = raw?.minority_owned_indicator;
		this.minorityType = raw?.minority_type;
		this.naics01Code = raw?.naics_01_code;
		this.naics01Description = raw?.naics_01_description;
		this.naics02Code = raw?.naics_02_code;
		this.naics02Description = raw?.naics_02_description;
		this.naics03Code = raw?.naics_03_code;
		this.naics03Description = raw?.naics_03_description;
		this.naics04Code = raw?.naics_04_code;
		this.naics04Description = raw?.naics_04_description;
		this.naics05Code = raw?.naics_05_code;
		this.naics05Description = raw?.naics_05_description;
		this.naics06Code = raw?.naics_06_code;
		this.naics06Description = raw?.naics_06_description;
		this.newBusinessIndicator = raw?.new_business_indicator;
		this.nonProfitIndicator = raw?.non_profit_indicator;
		this.numOfPcsRange = raw?.num_of_pcs_range;
		this.numOfPcsTotal = raw?.num_of_pcs_total;
		this.numberOfYearsInBusiness = raw?.number_of_years_in_business;
		this.numberOfYearsInBusinessRange = raw?.number_of_years_in_business_range;
		this.officeEquipmentExpenseRange = raw?.office_equipment_expense_range;
		this.officeEquipmentExpenseTotal = raw?.office_equipment_expense_total;
		this.operatingHoursFriday = raw?.operating_hours_friday;
		this.operatingHoursMonday = raw?.operating_hours_monday;
		this.operatingHoursSaturday = raw?.operating_hours_saturday;
		this.operatingHoursSunday = raw?.operating_hours_sunday;
		this.operatingHoursThursday = raw?.operating_hours_thursday;
		this.operatingHoursTuesday = raw?.operating_hours_tuesday;
		this.operatingHoursWednesday = raw?.operating_hours_wednesday;
		this.phone = raw?.phone;
		this.phoneAreaCode = raw?.phone_area_code;
		this.phoneSecondary = raw?.phone_secondary;
		this.phoneTollFree = raw?.phone_toll_free;
		this.plus4Code = raw?.plus4_code;
		this.populationRange = raw?.population_range;
		this.precision = raw?.precision;
		this.primaryExecutiveIndicator = raw?.primary_executive_indicator;
		this.primaryNumber = raw?.primary_number;
		this.primarySic2DigitCode = raw?.primary_sic_2digit_code;
		this.primarySic2DigitDescription = raw?.primary_sic_2digit_description;
		this.primarySic4DigitCode = raw?.primary_sic_4digit_code;
		this.primarySic4DigitDescription = raw?.primary_sic_4digit_description;
		this.primarySicCode = raw?.primary_sic_code;
		this.primarySicDescription = raw?.primary_sic_description;
		this.publicIndicator = raw?.public_indicator;
		this.rdi = raw?.rdi;
		this.rentExpenseRange = raw?.rent_expense_range;
		this.rentExpenseTotal = raw?.rent_expense_total;
		this.secondary01Sic7DigitCode = raw?.secondary_01_sic_7digit_code;
		this.secondary01Sic7DigitDescription = raw?.secondary_01_sic_7digit_description;
		this.secondary02Sic7DigitCode = raw?.secondary_02_sic_7digit_code;
		this.secondary02Sic7DigitDescription = raw?.secondary_02_sic_7digit_description;
		this.secondary03Sic7DigitCode = raw?.secondary_03_sic_7digit_code;
		this.secondary03Sic7DigitDescription = raw?.secondary_03_sic_7digit_description;
		this.secondary04Sic7DigitCode = raw?.secondary_04_sic_7digit_code;
		this.secondary04Sic7DigitDescription = raw?.secondary_04_sic_7digit_description;
		this.secondary05Sic7DigitCode = raw?.secondary_05_sic_7digit_code;
		this.secondary05Sic7DigitDescription = raw?.secondary_05_sic_7digit_description;
		this.secondaryDesignator = raw?.secondary_designator;
		this.secondaryNumber = raw?.secondary_number;
		this.sectionalCenterFacility = raw?.sectional_center_facility;
		this.smallBusinessIndicator = raw?.small_business_indicator;
		this.sourceTitle = raw?.source_title;
		this.squareFootage = raw?.square_footage;
		this.squareFootageRange = raw?.square_footage_range;
		this.standardizedTitle = raw?.standardized_title;
		this.standardizedTitleRank = raw?.standardized_title_rank;
		this.stateAbbreviation = raw?.state_abbreviation;
		this.stockExchange = raw?.stock_exchange;
		this.streetName = raw?.street_name;
		this.streetPostdirection = raw?.street_postdirection;
		this.streetPredirection = raw?.street_predirection;
		this.streetSuffix = raw?.street_suffix;
		this.subHqCityName = raw?.sub_hq_city_name;
		this.subHqCompanyName = raw?.sub_hq_company_name;
		this.subHqId = raw?.sub_hq_id;
		this.subHqNumberOfCompanies = raw?.sub_hq_number_of_companies;
		this.subHqStateAbbreviation = raw?.sub_hq_state_abbreviation;
		this.technologyExpenseRange = raw?.technology_expense_range;
		this.technologyExpenseTotal = raw?.technology_expense_total;
		this.telecomExpenseRange = raw?.telecom_expense_range;
		this.telecomExpenseTotal = raw?.telecom_expense_total;
		this.tickerSymbol = raw?.ticker_symbol;
		this.timeZone = raw?.time_zone;
		this.url = raw?.url;
		this.urlFacebook = raw?.url_facebook;
		this.urlInstagram = raw?.url_instagram;
		this.urlLinkedin = raw?.url_linkedin;
		this.urlTwitter = raw?.url_twitter;
		this.urlYelp = raw?.url_yelp;
		this.urlYoutube = raw?.url_youtube;
		this.utilitiesExpenseRange = raw?.utilities_expense_range;
		this.utilitiesExpenseTotal = raw?.utilities_expense_total;
		this.webmailIndicator = raw?.webmail_indicator;
		this.yearCurrent = raw?.year_current;
		this.yearCurrentEmployeeCount = raw?.year_current_employee_count;
		this.yearEstablished = raw?.year_established;
		this.yearFourPrior = raw?.year_four_prior;
		this.yearFourPriorEmployeeCount = raw?.year_four_prior_employee_count;
		this.yearFourPriorEmployeeGrowth = raw?.year_four_prior_employee_growth;
		this.yearOnePrior = raw?.year_one_prior;
		this.yearOnePriorEmployeeCount = raw?.year_one_prior_employee_count;
		this.yearOnePriorEmployeeGrowth = raw?.year_one_prior_employee_growth;
		this.yearThreePrior = raw?.year_three_prior;
		this.yearThreePriorEmployeeCount = raw?.year_three_prior_employee_count;
		this.yearThreePriorEmployeeGrowth = raw?.year_three_prior_employee_growth;
		this.yearTwoPrior = raw?.year_two_prior;
		this.yearTwoPriorEmployeeCount = raw?.year_two_prior_employee_count;
		this.yearTwoPriorEmployeeGrowth = raw?.year_two_prior_employee_growth;
		this.zipcode = raw?.zipcode;
	}
}
